# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.SmallIntegerField(choices=[(0, 'Autonomous Region of Bougainville'), (1, 'Central'), (2, 'Chimbu'), (3, 'East New Britain'), (4, 'East Sepik)'), (5, 'Eastern Highlands'), (6, 'Enga'), (7, 'Gulf'), (8, 'Hela'), (9, 'Jiwaka'), (10, 'Madang'), (11, 'Manus'), (12, 'Milne Bay'), (13, 'Morobe'), (14, 'National Capital District'), (15, 'New Ireland'), (16, 'Oro (Northern)'), (17, 'Sandaun(West Sepik)'), (18, 'Southern Highlands'), (19, 'West New Britain'), (20, 'Western(Fly)'), (21, 'Western Highlands')], default=14)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.SmallIntegerField(choices=[(0, '------'), (1, 'male'), (2, 'female')], default=0)),
                ('mobile', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_number', models.CharField(editable=False, max_length=6, unique=True, verbose_name='Patient Number')),
                ('date_of_birth', models.DateField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentistapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '------'), (1, 'new'), (3, 'review')], default=0)),
                ('comments', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dentistapp.Patient')),
            ],
        ),
    ]
