# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=1024, null=True)),
                ('user_anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnamnesisCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AnamnesisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1024)),
                ('location', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('id_number', models.CharField(max_length=64)),
                ('address', models.TextField(max_length=256)),
                ('mobile', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDetected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.ProblemCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_baby_tooth', models.BooleanField(default=False)),
                ('tooth', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
                ('final_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Step')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Step')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitAnamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Anamnesis')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.AnamnesisCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_time', models.DateTimeField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Visit')),
                ('visit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.VisitStatus')),
            ],
        ),
        migrations.CreateModel(
            name='VisitSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_time', models.DateTimeField()),
                ('notes', models.TextField(max_length=512)),
                ('problem_detected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.ProblemDetected')),
                ('treatment_steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.TreatmentSteps')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Visit')),
            ],
        ),
        migrations.AddField(
            model_name='problemdetected',
            name='selected_treatement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectedtreatment', to='dentalapp.Treatment'),
        ),
        migrations.AddField(
            model_name='problemdetected',
            name='suggested_treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestedtreatment', to='dentalapp.Treatment'),
        ),
        migrations.AddField(
            model_name='problemdetected',
            name='tooth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Tooth'),
        ),
        migrations.AddField(
            model_name='problemdetected',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Visit'),
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.Patient'),
        ),
        migrations.AddField(
            model_name='anamnesiscatalog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalapp.AnamnesisType'),
        ),
    ]
